[package]
name = "sahko"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
eyre = "0.6"
chrono = { version = "0.4.26", features = ["serde"] }
env_logger = "0.11"
gpio-cdev = "0.6.0"
pico-args = "0.5.0"
log = "0.4"
